### PR TITLE
Remove the 'HTACG' text from the logo.

### PR DESCRIPTION
**Pull request by anssiko**
I noticed that on smaller screens (e.g. on iPhone 6s, see the attached screenshot) the "HTACG" text in `htacg-logo.svg` overlaps with `<h1>Tidy</h1>` at http://www.html-tidy.org/ (also somewhat with `<h1>HTACG</h1>` at http://www.htacg.org/) making the text unreadable.

This PR fixes the issue by removing the "HTACG" text from `htacg-logo.svg`.

Related to #1.

htacg-logo-iphone_6s

### CODE REVIEW

**Comment by balthisar** [comment]
Hmmm... I should have checked smaller screens. I'll merge the PR for now, but in the longer run I'll revert it and find a more responsive solution. The HTACG is really a critical part of the logo.

It's also made me realize I need to ensure the correct font is installed, or choose another web-safe font, so no harm in removing it until I fix that.

**Comment by anssiko** [comment]
Thanks!

**Comment by balthisar** [comment]
@anssiko, no problem with the PR, short-lived as it was! I modified the SVG to use outlines, and now use an alternate image for narrow screens that moves the HTACG above the broom handle. I don't like the balance of the appearance, but HTACG/branding, whatever. I might consider removing the HTACG on just narrow screens, as it would look better, and still be visible on wide displays.

**Comment by anssiko** [comment]
Liking how the SVG now adapts to the narrow screen.

I also think dropping HTACG on narrow screens would be ideal. On http://www.htacg.org/ in particular you now have the text HTACG repeated twice which seems redundant.

**Pull request merged**
